name: Release Only

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latestt

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 22

      - name: Extract version from tag
        id: set_version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
        shell: bash

      - name: Build shaded jar
        run: mvn -B clean package

      - name: Rename jar for jpackage
        run: mv target/minesweeper-1.0-SNAPSHOT.jar target/Minesweeper-${VERSION}.jar
        shell: bash

      - name: Upload artifacts to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/Minesweeper-${{ env.VERSION }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
